name: trussframeASAP-RL
channels:
  - conda-forge
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2024.8.30
  - libffi=3.4.2
  - liblzma=5.6.3
  - libzlib=1.3.1
  - ncurses=6.5
  - tzdata=2024b
  - liblzma-devel=5.6.3
  - libsqlite=3.47.0
  - openssl=3.4.0
  - readline=8.2
  - tk=8.6.13
  - xz-gpl-tools=5.6.3
  - xz-tools=5.6.3
  - xz=5.6.3
  - python=3.10.15
  - setuptools=75.6.0
  - wheel=0.45.1
  - pip=24.3.1